# Use an official PostgreSQL runtime as the base image
FROM postgres:13

# Set environment variables
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB postgres

# Run the SQL scripts when the container launches
CMD ["postgres"]